var backgrounds = new Array();
var geologiaText = "La geoarcheologia è un metodo di indagine archeologico che si serve dell'ausilio di metodi geologici come la stratigrafia o la geomorfologia. L'approccio &#34;geoarcheologico&#34; è un approccio di tipo ambientale, ossia cerca di situare il sito archeologico in un contesto più ampio che è quello del territorio in cui il sito è inserito. Si cerca in questo modo di ricostruire non solo la storia materiale e culturale del sito, ma anche quella delle risorse (per esempio idriche) che il territorio offriva. A differenza di altri &#34;approcci&#34; nello studio di un sito archeologico, qui il terreno che costituisce la zona delimitata e definita come situ viene scavata orizzonte per orizzonte, livello per livello. I reperti vengono raccolti e catalogati per procedere poi in altra sede ad una loro identificazione e ricostruzione.";
var geologiaImg = "https://upload.wikimedia.org/wikipedia/commons/9/9b/Gypsum_cones.jpg";
var geologiaTextAttribution="https://it.wikipedia.org/wiki/Geoarcheologia";
var geologiaImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/9/9b/Gypsum_cones.jpg"

var paleobotanicaText = "La paleobotanica, dal Greco paleon = vecchio e botanikos = botanico, è la disciplina che si occupa dello studio delle alghe e delle piante fossili presenti nei sedimenti, e costituisce una branca della paleontologia. Risulta fondamentale per la ricostruzione degli ecosistemi ancestrali e per gli studi sull'evoluzione delle piante, oltre ad essere un valido supporto alle ricerche sulle variazioni climatiche. In maniera analoga si applica ai contesti antropici, sotto il nome di archeobotanica, contribuendo alla ricostruzione del paesaggio ed individuando l'uso tecnologico, economico e alimentare delle piante da parte dell'uomo nel passato. Per identificare vari tipi di resti vegetali, si avvale di numerose sottodiscipline: antracologia, analisi dei fitoliti, foglie e cuticoli, paleocarpologia, palinologia. Una scienza strettamente collegata è la palinologia, lo studio del polline e delle spore attuali e fossili. La paleobotanica è importante per la ricostruzione degli ecosistemi e dei climi fossili ed è fondamentale per lo studio dell'evoluzione delle piante.Le indagini si concentrano sui cambiamenti nella vegetazione (in rapporto al clima e alla situazione ambientale) e sull'analisi degli interventi umani sull'ambiente, facendo particolare attenzione alla dieta e all'economia.";
var paleobotanicaImg = "https://upload.wikimedia.org/wikipedia/commons/f/f6/ViburnumFossil.jpg";
var paleobotanicaTextAttribution = "https://it.wikipedia.org/wiki/Paleobotanica";
var paleobotanicaImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/f/f6/ViburnumFossil.jpg";

var aereaText = "Nel campo dell'archeologia la fotografia aerea è uno strumento di indagine che consente di evidenziare tracce, non percepibili da terra, di resti interrati. Permette inoltre di cogliere, con una visione d'insieme, i reciproci rapporti spaziali dei ritrovamenti portati alla luce. Le fotografie, possono essere riprese verticalmente, o obliquamente. I migliori effetti si ottengono con fotografie scattate in diverse stagioni dell'anno e spesso possono essere utili immagini scattate al tramonto o all'alba, in condizioni di luce radente. Si possono utilizzare tecniche di ripresa all'infrarosso (termografia) che evidenziano le differenze termiche e di umidità nel terreno. I resti sepolti possono essere individuati per la presenza di minimi rilievi nel terreno in corrispondenza del sottostante materiale più compatto, oppure per le differenze di crescita nella vegetazione, che può essere ostacolata o rallentata nel suo sviluppo se ciò avviene in corrispondenza di resti sepolti piuttosto che in zone con terreno più profondo. Inoltre, la fotografia aerea a tappeto di una regione permette di individuare le grandi linee e l'orientamento delle suddivisioni agricole antiche (ad esempio la centuriazione romana), che spesso in pianura sono state conservate attraverso i secoli e hanno determinato l'orientamento delle vie di comunicazione antiche, spesso ricalcate anche da quelle moderne.";
var aereaImg = "https://upload.wikimedia.org/wikipedia/commons/3/30/Grezac.jpg";
var aereaTextAttribution = "https://it.wikipedia.org/wiki/Aerofotogrammetria#Archeologia";
var aereaImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/3/30/Grezac.jpg";
backgrounds.push({txt:geologiaText, txtAttribution: geologiaTextAttribution, img:geologiaImg, imgAttribution:geologiaImgAttribution});
backgrounds.push({txt:paleobotanicaText, txtAttribution: paleobotanicaTextAttribution, img:paleobotanicaImg, imgAttribution:paleobotanicaImgAttribution});
backgrounds.push({txt:aereaText, txtAttribution: aereaTextAttribution, img:aereaImg, imgAttribution:aereaImgAttribution});
