var backgrounds = new Array();
var geologiaText = "La geoarcheologia è un metodo di indagine archeologico che si serve dell'ausilio di metodi geologici come la stratigrafia o la geomorfologia. L'approccio &#34;geoarcheologico&#34; è un approccio di tipo ambientale, ossia cerca di situare il sito archeologico in un contesto più ampio che è quello del territorio in cui il sito è inserito. Si cerca in questo modo di ricostruire non solo la storia materiale e culturale del sito, ma anche quella delle risorse (per esempio idriche) che il territorio offriva. A differenza di altri &#34;approcci&#34; nello studio di un sito archeologico, qui il terreno che costituisce la zona delimitata e definita come situ viene scavata orizzonte per orizzonte, livello per livello. I reperti vengono raccolti e catalogati per procedere poi in altra sede ad una loro identificazione e ricostruzione.";
var geologiaImg = "img/servizi/geoarcheologia.png";
/*var geologiaImg = "https://upload.wikimedia.org/wikipedia/commons/9/9b/Gypsum_cones.jpg";
var geologiaTextAttribution="https://it.wikipedia.org/wiki/Geoarcheologia";
var geologiaImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/9/9b/Gypsum_cones.jpg"*/

var paleobotanicaText = "La paleobotanica, dal Greco paleon = vecchio e botanikos = botanico, è la disciplina che si occupa dello studio delle alghe e delle piante fossili presenti nei sedimenti, e costituisce una branca della paleontologia. Risulta fondamentale per la ricostruzione degli ecosistemi ancestrali e per gli studi sull'evoluzione delle piante, oltre ad essere un valido supporto alle ricerche sulle variazioni climatiche. In maniera analoga si applica ai contesti antropici, sotto il nome di archeobotanica, contribuendo alla ricostruzione del paesaggio ed individuando l'uso tecnologico, economico e alimentare delle piante da parte dell'uomo nel passato. Per identificare vari tipi di resti vegetali, si avvale di numerose sottodiscipline: antracologia, analisi dei fitoliti, foglie e cuticoli, paleocarpologia, palinologia. Una scienza strettamente collegata è la palinologia, lo studio del polline e delle spore attuali e fossili. La paleobotanica è importante per la ricostruzione degli ecosistemi e dei climi fossili ed è fondamentale per lo studio dell'evoluzione delle piante.Le indagini si concentrano sui cambiamenti nella vegetazione (in rapporto al clima e alla situazione ambientale) e sull'analisi degli interventi umani sull'ambiente, facendo particolare attenzione alla dieta e all'economia.";
var paleobotanicaImg = "https://upload.wikimedia.org/wikipedia/commons/f/f6/ViburnumFossil.jpg";
var paleobotanicaTextAttribution = "https://it.wikipedia.org/wiki/Paleobotanica";
var paleobotanicaImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/f/f6/ViburnumFossil.jpg";

var altaQuotaText = "Negli ultimi anni Arc-Team si è occupata di missioni e interventi di emergenza in alta quota. Tali interventi si sono resi sempre più necessari a causa dei problemi connessi ai cambiamenti climatici e al conseguente ritiro dei ghiacciai. Lo scioglimento del ghiaccio riporta in luce una grossa quantità di materiale, molto spesso di natura organica, il quale, una volta liberato dal ghiaccio, comincia rapidamente a deteriorarsi. Altra conseguenza altrettanto grave del ritiro dei ghiacciai è l'aumento di frane e smottamenti che mettono in serio pericolo i reperti.<br>La pianificazione di una missione archeologica in alta quota è un processo molto delicato, soprattutto per quanto riguarda l'aspetto logistico. I lavori svolti in questi ultimi anni hanno permesso alla nostra ditta di acquisire le competenze necessarie per pianificare in maniera ottimale un missione archeologica in alta quota.";
var altaQuotaImg = "img/servizi/alta_quota.png";

var orienteText = "Da oltre 10 anni Arc-Team supporta missioni universitarie nel Vicino e Medio Oriente, coordinando i lavori sul campo e occupandosi della documentazione digitalizzata delle evidenze archeologiche.";
var orienteImg = "img/servizi/oriente.png";

var preventivaText = "La legge sull'archeologia preventiva (D.Lgs. 163/2006) prevede una procedura di valutazione dell'impatto di opere pubbliche sul patrimonio archeologico in sede di progetto preliminare. Uno degli obiettivi principali che si pone l'archeologia preventiva è quello di conciliare la tutela del patrimonio con le esigenze operative di interventi edilizi, estrattivi o relativi a grandi opere infrastrutturali, che comportano lavori di scavo. La normativa vigente prevede due fasi: la prima integra la progettazione preliminare con l'esecuzione di carotaggi, prospezioni geofisiche e geochimiche, saggi archeologici e altri tipi di interventi solitamente concordati con la Soprintendenza Archeologica; la seconda integra la progettazione definitiva ed esecutiva con l'esecuzione di sondaggi e scavi, anche in estensione. Le fasi di indagine si concludono con la redazione di una relazione in cui viene fatta una valutazione delle evidenze o delle \"assenze\" archeologiche al fine di pianificare eventuali interventi di tutela o valorizzazione delle evidenze presenti, o di dichiarare l'area di interesse priva di rischio archeologico, nel caso venga rilevata l'assenza di evidenze archeologiche.";
var preventivaImg = "img/servizi/preventiva.png";

var subText = "Lo sviluppo delle conoscenze, sia nel campo della tecnica e dei materiali, quanto in quello della fisiologia, ha consentito il raggiungimento di quote, progressivamente più impegnative, inimmaginabili sino a pochi anni fa. Di conseguenza, il confronto con relitti sempre più profondi è divenuto tale che, lì dove la tecnica dell'immersione umana non è ancora giunta, ma dove arrivano batiscafi o veicoli subacquei filoguidati, è oramai possibile rilevare, documentare e recuperare giacimenti, relitti e reperti, a quote praticamente abissali. Questa affascinante scienza, che spesso viene erroneamente confusa con il solo recupero di antichi oggetti sommersi, è costituita da specifiche fasi, metodi, mansioni, materiali, attrezzature e normative. L'amore per la (ri) scoperta del passato, l'emozione per il rinvenimento di un reperto e la conseguente appassionata opera di ricostruzione e contestualizzazione storica del ritrovamento, necessitano anche di ogni sforzo teso alla tutela, conservazione e valorizzazione del patrimonio culturale. L'archeologia subacquea, pur ispirata dalle medesime regole che operano in quella terrestre, proprio a causa del diverso elemento nel quale l'operatore esplica l'attività – sott'acqua – comporta difficoltà particolari, tali da rendere problematico ogni intervento di studio, gestione, tutela e valorizzazione del patrimonio subacqueo ed anche per questo va considerata come scienza autonoma. Arc-Team è impegnata dal 2005 in progetti di archeologia subacquea in particolare in alcuni laghi alpini del Trentino";
var subImg = "img/servizi/sub.png";

var droneText = "Nel campo dell'archeologia la fotografia aerea è uno strumento di indagine che consente di evidenziare tracce, non percepibili da terra, di resti interrati. Permette inoltre di cogliere, con una visione d'insieme, i reciproci rapporti spaziali dei ritrovamenti portati alla luce. Le fotografie, possono essere riprese verticalmente, o obliquamente. I migliori effetti si ottengono con fotografie scattate in diverse stagioni dell'anno e spesso possono essere utili immagini scattate al tramonto o all'alba, in condizioni di luce radente. Si possono utilizzare tecniche di ripresa all'infrarosso (termografia) che evidenziano le differenze termiche e di umidità nel terreno. I resti sepolti possono essere individuati per la presenza di minimi rilievi nel terreno in corrispondenza del sottostante materiale più compatto, oppure per le differenze di crescita nella vegetazione, che può essere ostacolata o rallentata nel suo sviluppo se ciò avviene in corrispondenza di resti sepolti piuttosto che in zone con terreno più profondo. Inoltre, la fotografia aerea a tappeto di una regione permette di individuare le grandi linee e l'orientamento delle suddivisioni agricole antiche (ad esempio la centuriazione romana), che spesso in pianura sono state conservate attraverso i secoli e hanno determinato l'orientamento delle vie di comunicazione antiche, spesso ricalcate anche da quelle moderne.";
var droneImg = "https://upload.wikimedia.org/wikipedia/commons/3/30/Grezac.jpg";
var droneTextAttribution = "https://it.wikipedia.org/wiki/Aerofotogrammetria#Archeologia";
var droneImgAttribution = "https://upload.wikimedia.org/wikipedia/commons/3/30/Grezac.jpg";
backgrounds.push({txt:geologiaText, txtAttribution: "", img:geologiaImg, imgAttribution:""});
backgrounds.push({txt:paleobotanicaText, txtAttribution: paleobotanicaTextAttribution, img:paleobotanicaImg, imgAttribution:paleobotanicaImgAttribution});
backgrounds.push({txt:altaQuotaText, txtAttribution: "", img:altaQuotaImg, imgAttribution:""});
backgrounds.push({txt:orienteText, txtAttribution: "", img:orienteImg, imgAttribution:""});
backgrounds.push({txt:preventivaText, txtAttribution: "", img:preventivaImg, imgAttribution:""});
backgrounds.push({txt:subText, txtAttribution: "", img:subImg, imgAttribution:""});
backgrounds.push({txt:droneText, txtAttribution: droneTextAttribution, img:droneImg, imgAttribution:droneImgAttribution});
